apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gkt3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gkt3
    app.kubernetes.io/part-of: tkrw-pr712-0075-0003-app
  name: devfile-sample-gkt3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gkt3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gkt3
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-gkt3@sha256:50fb30a7701a36005c363710e8f5294c6b91f88b17a324a2d8a4ac2f0e3702a3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
